## Apache2 mod_http2 config

- name: config | module | http2 | Enable mod_http2
  apache2_module:
    name: http2
    state: present
    ignore_configcheck: yes
  notify:
    - Test apache2 and reload