## Apache2 mod_rewrite config

- name: config | module | rewrite | Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
    ignore_configcheck: yes
  notify:
    - Test apache2 and reload