## Apache2 mod_status config


- name: config | module | status | Enable mod_status
  apache2_module:
    name: status
    state: present
    ignore_configcheck: yes
  notify:
    - Test apache2 and reload
