---
- name: Converge
  hosts: all

  roles:
    - role: apache2
      vars:
        apache2__enable_mod_http2: True
        apache2__enable_mod_security2: True
        apache2__enable_mod_expires: True
        apache2__enable_mod_proxy_http: True
        apache2__vhosts:
            - name: www.test.local
              serveralias:
                - www2.test.local
              port80_enforce_ssl: True
              enable_port443: True
              admin_email: admin@test.local
              ssl_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
              ssl_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
              port443_directory:
                - path: /opt/netbox/netbox/static
                  provider: directory
                  options: ['FollowSymLinks', 'MultiViews']
                  require: ['all granted']
              port443_alias:
                - alias: /static
                  path: /opt/netbox/netbox/static
              port443_custom_parameters:
                - 'ProxyPreserveHost On'
                - 'RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}'
                - 'ProxyPass / http://127.0.0.1:8001/'
                - 'ProxyPassReverse / http://127.0.0.1:8001/'
